# Generated by Django 3.2.16 on 2022-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_genre_title_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, through='reviews.TitleGenre', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
