# Generated by Django 3.2.16 on 2022-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221117_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name_plural': 'Произведения'},
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(('year__lte', 2022)), name='year__lte=now_year'),
        ),
    ]
